name: bubble_label
description: A small Flutter package that shows a floating bubble label anchored to a child widget, and optional background overlay + simple show/dismiss animations.
license: MIT
issue_tracker: https://github.com/SoundSliced/bubble_label/issues
repository: https://github.com/SoundSliced/bubble_label
version: 6.1.2
homepage: https://github.com/SoundSliced/bubble_label

screenshots:
  - description: 'Bubble label example showing tap and long-press interactions with overlay and animation toggles'
    path: example/assets/example.gif

topics:
  - ui
  - overlay
  - tooltip
  - bubble
  - widget

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_packages: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
